title: Additi Pandey
description: This is my personal webpage.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
github:
  zip_url: https://drive.google.com/file/d/1RnSS2JVFjpYHhSGJHkuDTWqGAHhNe05Y/view?usp=sharing
