title: Additi Pandey
description: əˈdiːti ˈpʌndeɪ
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

github:
  url: https://github.com/cyclotomicextension
  zip_url: https://github.com/cyclotomicextension/cyclotomicextension.github.io/blob/cd6e1f7e62780f8d3c18f71e4edfb79fb2e57746/AdditiPandeyCV.pdf
  pink_url: https://github.com/cyclotomicextension/cyclotomicextension.github.io/blob/a6cdcad4bc335f1cca6419599361df4e301a76cb/Additi_Resume_2022_23.pdf

linkedin:
  url: https://www.linkedin.com/in/additi-pandey

orcid:
  url: https://orcid.org/0009-0006-9930-7118
google scholar:
  url: https://scholar.google.com/citations?user=5pLxSZgAAAAJ&hl=en&oi=ao
