title: Additi Pandey
description: This is my personal webpage.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
github:
  zip_url: https://github.com/cyclotomicextension/cyclotomicextension.github.io/blob/cd6e1f7e62780f8d3c18f71e4edfb79fb2e57746/AdditiPandeyCV.pdf
